### ISSUE TITLE
Container not start after Host reboot (Exit code 127)

### ISSUE THREAD

**Issue by barbuslex** [dockur/dnsmasq#4]
My config:
- Windows 11 x64
- WSL - Debian x64

Here my docker compose file :
```yaml
  dnsmasq:
    image: dockurr/dnsmasq
    container_name: dnsmasq
    environment:
      DNS1: "1.1.1.1"
      DNS2: "1.0.0.1"
    ports:
      - 53:53/udp
      - 53:53/tcp
    cap_add:
      - NET_ADMIN
    restart: always
    volumes:
      - ./dnsmasq/etc/dnsmasq.d/:/etc/dnsmasq.d/
      - ./dnsmasq/etc/dnsmasq-hosts.conf:/etc/dnsmasq-hosts.conf
    networks:
      entrypoint:
        ipv4_address: 172.18.0.254
```

All works perfectly... after host reboot... the container have exit code 127 : 
![image](https://github.com/dockur/dnsmasq/assets/113057/82f53746-6d48-4061-9245-04f4cd66573f)

If i start manually the container its works.

Have you an idea how to fix it please ?

Thanks
