### ISSUE TITLE
Process gets stuck and stops responding to requests 

### ISSUE THREAD

**Issue by coldsobolev** [dockur/dnsmasq#7]
Hello, I am using your image as DNS and DHCP server in an office environment and I run it with `network_mode: host`. For some reason, the container gets stuck and even restarting it takes a very long time. `docker logs` show nothing useful and even running it in debug mode is not useful. Any idea what could be causing this?

**Comment by danil-smirnov** [comment]
I have the same issue

**Comment by kda-jt** [comment]
Agreed, same problem here as well

**Comment by kda-jt** [comment]
I've set a healthcheck and a restart policy to my docker compose file, this way docker takes care of restarting the container if it fails.
```
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "nslookup", "home.lan", "192.168.1.60"]
      interval: 30s
      timeout: 10s
      retries: 15
      start_period: 15s
```
I haven't had any issues in a while, the container has not restarted since I last rebooted the host machine (I've checked the uptime on both). Will report back if I see any problems again

**Comment by bokunodev** [comment]
i stumbled upon similar issue. in my case dnsmasq always response instantaneously if i send the query through TCP. but it **sometimes** stuck if it through UDP. i used [dog](https://github.com/ogham/dog). what strange is that UDP query **always** success after i send TCP query (possibly fetched the record from cache instead of upstream).
it'd be very helpful if can anyone answer some of my questions.

1. what tool did you use test it? (eg. dig, drill, dog)
2. have you try to send the query through TCP instead of UDP?

thanks

**Comment by jganseman** [comment]
Same issue. I have, as per previous comments, to the docker-compose.yml added the following lines:

```
services:
  dnsmasq:
    [...]
    healthcheck:
      test: ["CMD-SHELL", "nslookup google.com >/dev/null 2>&1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  autoheal:
    image: willfarrell/autoheal:latest
    container_name: autoheal
    restart: unless-stopped
    environment:
      - AUTOHEAL_CONTAINER_LABEL=autoheal
      - AUTOHEAL_INTERVAL=3
      - AUTOHEAL_START_PERIOD=30
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    logging:
      driver: syslog
      options:
        tag: autoheal
```

This seems to provide some relief, but when the network is in (heavy) use, autoheal seems to intervene very regularly. On weekend days when the network is barely active, everything goes smooth. On office days, I can be facing a dnsmasq container reboot every 10 minutes or worse. 
It seems that either some kind of network traffic, or maybe just a particular volume of traffic at the wrong time, makes the entire thing stall? 
`docker logs -f autoheal` and `journalctl -fu docker` give me a few high level logging events, but this seems to be a very elusive problem, I haven't been able to debug it further yet...

EDIT 1: I tried to solve the problem by replacing dockurr/dnsmasq with [4km3/docker-dnsmasq](https://github.com/4km3/docker-dnsmasq) . Your favorite AI assistant can help you write a functionally equivalent docker-compose.yml based on your current dockurr/dnsmasq one. After which the following did the trick:
```
docker compose pull
docker compose down
docker compose up -d
docker compose logs -f dnsmasq
```
EDIT 2:  4km3/docker-dnsmasq boots much snappier, but has exact the same problem in `network_mode:host`. The problem must be in dnsmasq itself and/or how docker networking deals with it, not in the containers that run it. Either that, or we all run some common component that trips up dnsmasq in our networks. Anyone else using Wireguard to connect to the network on which dnsmasq runs, or having a Proxmox cluster in their network?
